# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervip',
            name='mobile_number',
            field=models.IntegerField(default=''),
        ),
    ]
