# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0005_auto_20190102_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
