# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0007_personalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': 'PersonalINFO'},
        ),
        migrations.AlterModelOptions(
            name='vipwinner',
            options={'verbose_name_plural': 'VipWinner'},
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
