# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0008_auto_20190106_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('facephoto', models.ImageField(max_length=2500, upload_to=b'uploadedimages')),
                ('standingposephoto', models.ImageField(max_length=2500, upload_to=b'uploadedimages')),
                ('sideposephoto', models.ImageField(max_length=2500, upload_to=b'uploadedimages')),
                ('stylishposephoto', models.ImageField(max_length=2500, upload_to=b'uploadedimages')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
