# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-20 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0009_photoportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoportfolio',
            options={'verbose_name_plural': 'PhotoPortFolio'},
        ),
    ]
