# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-03 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0012_applicantstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantstatus',
            name='profilecompleted',
        ),
    ]
