# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipapi', '0014_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipwinner',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
